import React, { useState } from 'react';
import {
  Container,
  Form,
  Button,
  Card,
  Alert,
  Row,
  Col
} from 'react-bootstrap';
import { Brain } from 'lucide-react';
import { analyzeCity } from '../services/insightService';
import InsightCard from '../components/insights/InsightCard';
import TypingIndicator from '../components/common/TypingIndicator';

const Insights = () => {
  const [formData, setFormData] = useState({
    city: '',
    province: '',
    additional: ''
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [insights, setInsights] = useState(null);
  const [showResults, setShowResults] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setShowResults(false);

    try {
      const data = await analyzeCity(formData);
      setInsights(data);
      // Add a small delay before showing results to ensure smooth transition
      setTimeout(() => setShowResults(true), 500);
    } catch (err) {
      setError(err.response?.data?.message || err.message || 'Failed to analyze city insights');
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  return (
    <Container className="py-4">
      <Card className="mb-4">
        <Card.Header>
          <h4 className="mb-0">City Insights Analysis</h4>
        </Card.Header>
        <Card.Body>
          <Form onSubmit={handleSubmit}>
            <Row className="mb-3">
              <Col md={6}>
                <Form.Group className="mb-3">
                  <Form.Label>City<span className='text-danger'> *</span></Form.Label>
                  <Form.Control
                    type="text"
                    name="city"
                    value={formData.city}
                    onChange={handleInputChange}
                    required
                    placeholder="Enter city name"
                  />
                </Form.Group>
              </Col>
              <Col md={6}>
                <Form.Group className="mb-3">
                  <Form.Label>Province<span className='text-danger'> *</span> </Form.Label>
                  <Form.Control
                    type="text"
                    name="province"
                    value={formData.province}
                    onChange={handleInputChange}
                    required
                    placeholder="Enter province"
                  />
                </Form.Group>
              </Col>
            </Row>

            <Form.Group className="mb-4">
              <Form.Label>Special Conditions <span className='text-muted'>&#40;Optional&#41;</span> </Form.Label>
              <Form.Control
                as="textarea"
                name="additional"
                value={formData.additional}
                onChange={handleInputChange}
                rows={3}
                placeholder="Enter any special conditions or requirements..."
              />
            </Form.Group>

            <div className="d-grid">
              <Button
                type="submit"
                variant="primary"
                disabled={loading}
                className="d-flex align-items-center justify-content-center gap-2 col-md-2 col-6 mx-auto"
              >
                {loading ? (
                  <>
                    <Brain className="rotating-spin" size={20} />
                    <span>Analyzing...</span>
                  </>
                ) : (
                  'Analyze City'
                )}
              </Button>
            </div>
          </Form>
        </Card.Body>
      </Card>

      {error && (
        <Alert variant="danger" className="mb-4">
          {error}
        </Alert>
      )}

      {loading && <TypingIndicator />}

      {insights && showResults && (
        <>
          <div className="text-center mt-4 text-info border border-danger bg-white p-3 font-italic mx-auto"> <img src="/warning.png" height={15}
            alt="Warning icon"></img> We cannot guarantee the accuracy of the data provided. This is just an estimate and generated by AI. </div>
          <div className="insights-results mt-4">
            {Object.entries(insights.insights.sections).map(([key, section], sectionIndex) => (
              <InsightCard
                key={key}
                title={section.title}
                content={section.content}
                startTyping={true}
              />
            ))}
          </div>
        </>
      )}
    </Container>
  );
};

export default Insights;